### ISSUE TITLE
Formularz zapisu zawodnika do turnieju

### ISSUE THREAD

**Issue by Szambelan** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#104]
- [x] create BottomSheet
- [x] testy
- [x] Sprawdzanie poprawnosci przy wypelnianiu
- [x] Pokazywanie bledu jesli po kliknieciu ZAPISZ ZAWODNIKA juz jest taki zawodnik (to jakos API powinno zwrocic)
- [x] Tworzenie profilu zawodnika po kliknieciu przycisku.
- [ ] Po poprawnym utworzeniu profilu od razu wysylanie requestu zapisania na turniej, w kontekście którego to zostało otwarte. (**przeniesione do osobnego taska! -** #131 )

![image](https://user-images.githubusercontent.com/31566345/112507204-bcf55800-8d8e-11eb-8d4d-d7f32705dd66.png)

**Comment by nowakprojects** [comment]
Jeszcze przydalaby sie 
- [ ] Sprawdzanie poprawnosci przy wypelnianiu
- [ ] Pokazywanie bledu jesli po kliknieciu ZAPISZ ZAWODNIKA juz jest taki zawodnik (to jakos API powinno zwrocic)
- [ ] Po poprawnym utworzeniu profilu od razu wysylanie requestu zapisania na turniej, w kontekście którego to zostało otwarte.
