### ISSUE TITLE
Tournament Tables Module | Table reservation for a tournament

### ISSUE THREAD

**Issue by lamparina** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#11]
Kryteria akceptacji

- [x] Utworzyć nowy moduł (tournament-tables)
- [x] Zaimplementować komendę odpowiedzialną za przypisanie stołu do turnieju oraz jej handler
- [x] Zaimplementować event, który powiadamia o rezerwacji stołu dla danego turnieju
- [ ] Stworzyć schemat przypisanych stołów
- [ ] Zadeklarować moduł w app.ts

**Comment by nowakprojects** [comment]
Fajnie jakbys opisala co trzeba zrobic :) Podobnie jak:
https://github.com/nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments/issues/5

**Comment by lamparina** [comment]
Trzeba najpierw wiedzieć, co trzeba zrobić :P

**Comment by nowakprojects** [comment]
Cos mi sie powaliło i już po notyfikacji myślałem, że ktoś wrzucił gotowy PR. Poziom endorfin niebezpiecznie wzrósł i równie szybko opadł :D 

To powzoruj się tym co napisał właśnie @tomdworniczak :) Jak już za długo nad tym siedzisz -to jest znak do konsultacji.
