### ISSUE TITLE
Doubles Tournament Module | Create tournament with teams (part 2)

### ISSUE THREAD

**Issue by tomdworniczak** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#17]
### Kryteria akceptacji
**Należy zweryfikować i skonsultować, a także ewentualnie uaktualnić przed rozpoczęciem prac nad zgłoszeniem.**

- [ ]  - stworzyć schema utworzonego turnieju i zaimplementować zapis do/odczyt z bazy danych Mongo
- [ ]  - stworzyć nowy endpoint typu GET, który będzie zwracał drużyny przypisane do danego turnieju
- [ ]  - zadeklarować moduł w app.ts

**Comment by nowakprojects** [comment]
Juz widze co zrobiles i bardzo ladnie krozystasz z zastanego kodu :) 

A propos punktu:
` - stworzyć nowy endpoint typu GET, który będzie zwracał wszystkie utworzone turnieje i przypisane do nich drużyny`
Preferowałbym endpoint GET, który zwraca pary dla danego turnieju :) Bo raczej to ma wiekszy sens. Ale oba też nawet możesz zrobić :) Tylko ten dla konkretnego turnieju myślę, że raczej będzie miał "większe wzięcie". Bo para ma sens w kontekście turnieju.

**Comment by tomdworniczak** [comment]
Racja, zwracanie par dla konkretnego turnieju pewnie będzie miało tutaj większy sens, z resztą nie wiem czy w dalszym flow nie powinien pojawić się jakiś get, który pokaże nam wszystkie turnieje (?)
