### ISSUE TITLE
Double "Elimination Tournament Tree" Module | part_1

### ISSUE THREAD

**Issue by PiotrWR** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#18]
### Kryteria akceptacji
**Należy zweryfikować i skonsultować, a także ewentualnie uaktualnić przed rozpoczęciem prac nad zgłoszeniem.**

- [x] utwórz nowy moduł drzewka turnieju (u Tomka: "DoublesTournamentModuleCore")
- [x] stwórz komendę rozpisującą drużyny na drzewo turniejowe (tournamentId, teams [] )
- [x] stwórz komend handlera ;) 
- [x] logika rozmieszczenia drużyn na drzewie (jak "DoublesTournament.ts")
- [ ] stwórz event który powiadamia o rozpisaniu drzewka
- [ ] stworzyć schemat utworzonego drzewka i zaimplementować zapis do i odczyt z bazy danych

**Comment by nowakprojects** [comment]
@PiotrWR Bardzo ładnie rozpisane. Dokładnie o to chodzi :)
