### ISSUE TITLE
Email Module | Logic for sending emails to new players

### ISSUE THREAD

**Issue by Szambelan** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#32]
### Kryteria akceptacji
**Należy zweryfikować i skonsultować, a także ewentualnie uaktualnić przed rozpoczęciem prac nad zgłoszeniem.**

- [x] utworzyć komendę wysłania wiadomości wraz z CommandHandlerem
- [x] sprawdzić i podpiąć logikę/moduł cokolwiek to jest do faktycznego wysłania mail'a!
- [x] utworzyć eventHandlera w module players-profiles (robocik) wywołujący CommandHandlera z modułu send emails
- [x] TESTY

![image](https://user-images.githubusercontent.com/31566345/110214506-275c5c00-7ea5-11eb-8420-34027ae7da0e.png)

### Dodatkowe uwagi:
Ja bym wysyłał spersonalizowanego mail'a (typu Cześć Marcin,  ...dziękuję za stworzenie konta na ....) od razu po poprawnym utworzeniu profilu gracza.

**Comment by nowakprojects** [comment]
Wygląda OK :) 

Pytania / dodatkowe rzeczy ode mnie:  
1. W tym przypadku players-profiles będzie zależał od modułu maili, czy moduł maili od players-profiles :) ? 
2. Spersonalizowany email to dobry pomysł - wszystko do tego masz w evencie. Jedyne co to bym pomysłam nad czymś w stylu: "Twój profil został utworzony" - bo w tym przypadku nie ważne czy utworzył go sam czy mu jakiś admin to zrobił. To profil a nie konto np. do logowania. Aktualnie nie mamy żadnej opcji z logowaniem.
3. Pomysl czy mail będzie textem czy htmlem. Raczej lepiej jest HTML, tzn. przydałby się jakiś szablon HTML maila gdzie podstawiasz imię. Bo wtedy można stylować itp. W najprostszym przypadku tym HTMLem moze byc zwykly tekst. 
4. Testując czy mail się wysyła możesz albo zamockować same wysyłanie maili, albo użyć czegoś co przechtywuje wysyłanie maili i wstaje w dockerze przed testem jak baza, w stylu: https://jfelix.info/blog/test-your-email-flow-with-mailhog-a-fake-smtp-server
5. Ten moduł możliwe, że nie będzie miał warstwy domain, albo będzie ona bardzo uboga ;) Bo to taki "moduł techniczny", który wysła maile :)

**Comment by nowakprojects** [comment]
6. Będziesz musiał w jakimś serwisie utworzyć adres email z jakiego będziemy wysyłać. Zrób jakikolwiek na razie - najlepiej na Gmailu :)

**Comment by Szambelan** [comment]
1. No ja rozumiem, że moduł maili od players-profiles. Zakładamy konto to event o utworzeniu idzie do modułu mail'i, który wysyła email.
2. A no faktycznie ... trochę racja, że pomyliłem to z rejestracją, hmmm w sumie sądziłem, że tym samym możemy klepnąć rejestrację, bo czemu by nie? Chyba nic nie stoi na przeszkodzie.
3. to pewnie wyjdzie w trakcie jak doczytam o tym "Serwer SMTP (np. Gmail) lub usługa typu MailerLite / MailChimp", ale dobrze wiedzieć na zaś
4. no to widzę, że nieźle się wpakowałem :-|. Mam zacząć od testów? Bo tutaj tak chyba fajnie jakby udało mi się jakoś to podpiąć i faktycznie bym widział, że idą maile :-)
5. no w sumie fakt, nie będzie zbytnio co tu sprawdzać. Pewnie wyjdzie w trakcie
6. okey

**Comment by nowakprojects** [comment]
1. Tutaj warto pomyśleć co brać pod uwagę przy wyznaczaniu zależności modułów (czyli w tym przypadku gdzie będzie event handler wykonujący command wysyłający mail). Zasada Open-Closed (otwarty na rozszerzenia, zamknięty na zmiany). Załóżmy, że będzie teraz 5 kolejnych innych modułów (np. rozpoczęcie meczów będzie wysyłać maila, zakończenie turnieju itp.). Mógłbyś rozważyć 2 przypadki? I zobaczyć gdzie jest mniej modułów do wprowadzania zmiany przy dokładaniu nowego przypadku gdzie wysyłamy mail? I co powinno wiedzieć o sobie - czy maile wiedzą o wszystkich przypadkach jak je wysyłasz? Czy mail to mail, a Ty decydujesz co w nim napiszesz (Ty jako człowiek albo jakiś inny moduł)? Spróbuj to rozpisać, bo nie chcę, żebyście ślepo szli za tym co mówię :) Bo już na modelu możesz zaobserwować, że "robociki", które biorą event i wysyłają command są w danym module (w przypadku tournament-registrations). 

2. Na razie nie mamy czegoś takiego. Profile graczy potrzebują rejestracji? Nie. Ktoś może chceć tworzyć je ręcznie jako jakiś "admin" i tak jest teraz. Bo np. nie będziemy wymagac, żeby każdy kto przyjdzie na turniej i nawet nie wie jaki miał system zaraz wchodził i się rejestrował. 

3. Tak, obczaj co warto :) 

4. Jak dasz radę.

**Comment by Szambelan** [comment]
1. no właśnie tych robocików to jeszcze nie kumam z miro ... chyba przydałoby się to wiedzieć. Też o tym myślałem, że tych maili będzie pewnie więcej, więc tym samym lepiej byłoby zrobić  moduł wysyłania mail'i i ten moduł podpinać do tych, które będą chciały maila wysyłać. 
Bo na odwrót to za każdym razem trzeba będzie dopisywać przechwytywanie eventów w email-module i całą jego obsługę, więc raczej wyjdzie więcej roboty...

2. ok

**Comment by Szambelan** [comment]
1. 
![image](https://user-images.githubusercontent.com/31566345/109954377-8f624500-7ce1-11eb-8809-97f3018165a0.png)
no to na pierwszy rzut oka wydaję się to poniższe jako mniej roboty na przyszłość w celu wysyłania maili z nowych/innych modułów

**Comment by nowakprojects** [comment]
> 1. no właśnie tych robocików to jeszcze nie kumam z miro ... chyba przydałoby się to wiedzieć. Też o tym myślałem, że tych maili będzie pewnie więcej, więc tym samym lepiej byłoby zrobić  moduł wysyłania mail'i i ten moduł podpinać do tych, które będą chciały maila wysyłać.
>    Bo na odwrót to za każdym razem trzeba będzie dopisywać przechwytywanie eventów w email-module i całą jego obsługę, więc raczej wyjdzie więcej roboty...
> 2. ok

1. Dokładnie jak napisałeś :) Zmiana w każdym innym module powodowałaby nam zmianę w mailach. A jak wystawiamy command z maili i inne moduły uderzają do niego, to maila już nigdy nie zmieniamy. I te inne moduły mają wiedzę o np. imieniu, żeby skomponować maila.

**Comment by Szambelan** [comment]
dobra to zaktualizowałem opis taska
Dzięki!
