### ISSUE TITLE
Doubles Tournament Module | Create tournament with teams (part 1)

### ISSUE THREAD

**Issue by tomdworniczak** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#5]
### Kryteria akceptacji
**Należy zweryfikować i skonsultować, a także ewentualnie uaktualnić przed rozpoczęciem prac nad zgłoszeniem.**

- [x]  - utworzyć nowy moduł turnieju
- [x]  - zaimplementować komendę odpowiedzialną za utworzenie turnieju z drużynami oraz jej handler
- [x]  - zaimplementować funkcję, która nadaje drużynom ich turniejowe identyfikatory
- [x]  - zaimplementować event, który powiadamia o utworzeniu turnieju
- [x]  - stworzyć schema utworzonego turnieju i zaimplementować zapis do/odczyt z bazy danych
- [x]  - zadeklarować moduł w app.ts

### Dodatkowe uwagi
Ostatnie dwa podpunkty przeniesione do drugiej części zadania #17

**Comment by nowakprojects** [comment]
Zdaje się OK :) Ale jeszcze trzeba utworzyć sam moduł turnieju. I w nim zadeklarować handler. Spójrz na testy jak robimy - nie uderzamy do samego handlera tylko moduł jest taka czarna skrzynka, która dostaje komendę i publikuje event :) Albo dostaje event i publikuje inny event. No i na koniec moduł trzeba zadeklarować w app.ts.

**Comment by tomdworniczak** [comment]
No no, mam utworzony cały nowy moduł pt double-tournament-module :P i tam zawarte są komendy event i handlery, jakoś mi nie wpadło do głowy, żeby to napisać w tasku, bo było dla mnie oczywiste :D

**Comment by nowakprojects** [comment]
Te //TODO To raczej nie potrzebne :) Ja to zostawiłem w template jak w kodzie - tzn. wpisz tutaj jakis punkt do zrobienia.
