### ISSUE TITLE
Email Module | Add possibility to print email in console.log when docker is turn off

### ISSUE THREAD

**Issue by Szambelan** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#54]
- [x] make class like NodeMailerEmailSender but to print mails in console via console.log
- [x] remove NODEMAILER_USER and NODEMAILER_PASSWORD from .env and add it to discord - add note how to use it

**Comment by nowakprojects** [comment]
And the last one:
- Change the password for email account :)
