### ISSUE TITLE
Players Profiles Module | POST method with its logic

### ISSUE THREAD

**Issue by Szambelan** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#6]
## Stworzyć całą logikę dodania nowego profilu playera - w szczególności:

- [x] Utworzyć endpoint POST /players-profiles
- [x] Utworzyć obiekt domenowy wraz z metodą do jego zapisu
- [x] Stworzyć command w application > command wraz z jej commandHandlerem
- [x] Napisać odpowiedni query w application > query (do zapisu będzie również potrzebne query FindAll, które sprawdzi czy nie próbujemy zapisać już istniejącego gracza)
- [x] stworzyć PlayersProfilesRepository w application
- [x] utworzyć PlayerProfileModuleCore, który zwróci nam command i query handlers
- [x] stworzyć folder core > presentation, w którym będą utworzone obiekty do zwrócenia z bazy dancyh, RestApiModule oraz router
- [x] TESTY!

Poniższy obrazek przedstawia jaką część taska obejmuje kod
![image](https://user-images.githubusercontent.com/31566345/109398151-2c685b00-793b-11eb-9255-7efccc39fe21.png)

**Comment by nowakprojects** [comment]
Daj nazwę taska bardziej opisowa :) Bo to jest zapewne tylko kawałek modułu. Stawiam, że kiedyś dodamy inne komendy jak np. ChangeUserPhoneNumber itp.

**Comment by Szambelan** [comment]
> Daj nazwę taska bardziej opisowa :) Bo to jest zapewne tylko kawałek modułu. Stawiam, że kiedyś dodamy inne komendy jak np. ChangeUserPhoneNumber itp.

Tak tak to pozmieniam :-)
No właśnie się zastanawiam, czy nie walnąć PR'a jako cały moduł, bo tak mam trochę zaczęte i do POST i do GET i na tę chwilę ciężko mi to rozdzielić, bo nie wiem jeszcze co gdzie się przyda, ALE możliwe, że jak napiszę test do jednej z tej metody to się sytuacja wyklaruje i wtedy może uda mi się to podzielić na dwa osobne PR'y i taski.

Zapewne też przyda się GET na `/players-profiles/:id`?

**Comment by nowakprojects** [comment]
> > Daj nazwę taska bardziej opisowa :) Bo to jest zapewne tylko kawałek modułu. Stawiam, że kiedyś dodamy inne komendy jak np. ChangeUserPhoneNumber itp.
> 
> Tak tak to pozmieniam :-)
> No właśnie się zastanawiam, czy nie walnąć PR'a jako cały moduł, bo tak mam trochę zaczęte i do POST i do GET i na tę chwilę ciężko mi to rozdzielić, bo nie wiem jeszcze co gdzie się przyda, ALE możliwe, że jak napiszę test do jednej z tej metody to się sytuacja wyklaruje i wtedy może uda mi się to podzielić na dwa osobne PR'y i taski.
> 
> Zapewne też przyda się GET na `/players-profiles/:id`?

Głównie chodziło o to, że nigdy nie wiemy czy to jest "finish". Kod jest otwarty na rozbudowe i pewnie kiedyś coś dołożymy do tego modułu :) A jak opiszemy co robimy, że robisz jakąś częśc to wtedy wiemy o co chodziło.

Pewnie się przyda ten dodatkowy GET, ale endpointy zawsze możemy dorabiać jeszcze przy robieniu potem UIa w kolejnym tasku :) 
Więc teraz bym nie tracił na to czasu, bo przy dobrze zrobionych commandach i queries to tylko formalność.
I łatwo to dodać później bez modyfikacji tego co jest. POST koniecznie, bo jest u nas "wejściem" do apliakcji - tutaj jak na razie nikt inny nie wysyła commanda. Jak Ci szybko pójdzie to możesz zrobić jak napisałeś, ale długo nad tym nie siedź.

**Comment by Szambelan** [comment]
> > > Daj nazwę taska bardziej opisowa :) Bo to jest zapewne tylko kawałek modułu. Stawiam, że kiedyś dodamy inne komendy jak np. ChangeUserPhoneNumber itp.
> > 
> > 
> > Tak tak to pozmieniam :-)
> > No właśnie się zastanawiam, czy nie walnąć PR'a jako cały moduł, bo tak mam trochę zaczęte i do POST i do GET i na tę chwilę ciężko mi to rozdzielić, bo nie wiem jeszcze co gdzie się przyda, ALE możliwe, że jak napiszę test do jednej z tej metody to się sytuacja wyklaruje i wtedy może uda mi się to podzielić na dwa osobne PR'y i taski.
> > Zapewne też przyda się GET na `/players-profiles/:id`?
> 
> Głównie chodziło o to, że nigdy nie wiemy czy to jest "finish". Kod jest otwarty na rozbudowe i pewnie kiedyś coś dołożymy do tego modułu :) A jak opiszemy co robimy, że robisz jakąś częśc to wtedy wiemy o co chodziło.
> 
> Pewnie się przyda ten dodatkowy GET, ale endpointy zawsze możemy dorabiać jeszcze przy robieniu potem UIa w kolejnym tasku :)
> Więc teraz bym nie tracił na to czasu, bo przy dobrze zrobionych commandach i queries to tylko formalność.
> I łatwo to dodać później bez modyfikacji tego co jest. POST koniecznie, bo jest u nas "wejściem" do apliakcji - tutaj jak na razie nikt inny nie wysyła commanda. Jak Ci szybko pójdzie to możesz zrobić jak napisałeś, ale długo nad tym nie siedź.

Dobra zaktualizowałem tytuł i opis taska, chyba wygląda legitnie teraz, com? 
Jak to skończę i zrobię z tego już PR do review, wtedy zrobię kolejne taski związane z tym modułem :-)
