### ISSUE TITLE
Deployment aplikacji na środowisko developerskie

### ISSUE THREAD

**Issue by nowakprojects** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#8]
### Kryteria akceptacji
**Należy zweryfikować i skonsultować, a także ewentualnie uaktualnić przed rozpoczęciem prac nad zgłoszeniem.**

- [ ] Przygotować serwer (np. na Heroku), który uruchomi aplikację Node.js i umożliwi korzystanie z REST API.
- [ ] Środowisko powinno mieć skonfigurowane połączenie z bazą danych (np. poprzez MongoDB Atlas).
- [ ] GitHub Actions po każdym pushu na branch develop wdraża aplikację na przygotowane środowisko.

**Comment by tomdworniczak** [comment]
jak coś to powoli zacząłem się temu przyglądać, założyłem sobie Heroku i w międzyczasie postaram się ogarnąć jak to zaprzęgnąć do pracy dla nas :)

**Comment by nowakprojects** [comment]
Super! :) No to chyba możesz się przypisać i dać in progress? Jak coś to pytaj.
