### ISSUE TITLE
Double Tournament Module | Calling enqueued matches

### ISSUE THREAD

**Issue by lamparina** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#83]
### Kryteria akceptacji

- [x] publikowanie eventów TournamentTableWasBooked, TournamentTableWasReleased podczas przypisywania stołów do turnieju + update testów
- [x] testy
- [x] obsługa eventów MatchWasQueued, TournamentTableWasBooked, TournamentTableWasReleased, MatchWasCalled
- [x] wywołanie komendy CallMatch

**Comment by nowakprojects** [comment]
Ewentualnie możesz w module stołów rozważyć przy przypisywaniu stołów też od razu publikowanie eventow o wolnym/zajętym. Wtedy w tym tasku mogłabyś olać event przypisania i tylko tamte 2 supportowac :) Nawet to wygląda bardziej czysto, bo enkapsulujesz w granicach modułu stołów w jaki sposób są przydzielane do turnieju.

**Comment by lamparina** [comment]
Jest to jakaś myśl, dzięki! Bo już nie wiedziałam za co się zabrać najpierw :P
