### ISSUE TITLE
Pierwszy widok na fronendzie

### ISSUE THREAD

**Issue by PiotrWR** [nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#94]
Pierwszy widok na fronendzie:

- [ ] komponent logo
- [ ] komponent przycisku
- [ ] komponent stopki
- [ ] komponent ramki
- [ ] komponent tytułu

![image](https://user-images.githubusercontent.com/41823689/112050163-d315d500-8b50-11eb-88f3-0f0718fde398.png)

**Comment by nowakprojects** [comment]
Pamietaj, ze korzystamy z material UIa i takie komponenty jak Button już będą :)
